# ansible-pull setup
#
# on remote hosts, set up ansible to run periodically using the latest code
# from a particular checkout, in pull based fashion, inverting Ansible's
# usual push-based operating mode.
#
# This particular pull based mode is ideal for:
#
# (A) massive scale out
# (B) continual system remediation
#
# DO NOT RUN THIS AGAINST YOUR HOSTS WITHOUT CHANGING THE repo_url
# TO SOMETHING YOU HAVE PERSONALLY VERIFIED
#
#
---

- hosts: koombook
  remote_user: root

  vars:

    # File that ansible will use for logs
    logfile: /var/log/ansible-pull.log

    # Directory to where repository will be cloned
    workdir: /var/lib/ansible/local

    # Repository to check out -- YOU MUST CHANGE THIS
    # repo must contain a local.yml file at top level
    #repo_url: git://github.com/sfromm/ansible-playbooks.git
    repo_url: https://github.com/fheslouin/ansible-koombook.git

  tasks:

    - name: Install requiered package
      apt: name={{ item }} state=latest
      with_items:
       - python-pip
       - python-dev
       - python-setuptools
       - git
       - sudo

    - name: Installe ansible
      pip: name=ansible

    - name: Create local directory to work from
      file: path={{workdir}} state=directory owner=root group=root mode=0751

    - name: Create ansible hosts directory to work from
      file: path=/etc/ansible/ state=directory owner=root group=root mode=0751

    - name: Copy ansible inventory file to client
      copy: src=hosts dest=/etc/ansible/hosts
              owner=root group=root mode=0644

    - name: Create entry to clone/pull git repository
      template: src=templates/if-up.d.j2 dest=/etc/dhcp/dhclient-enter-hooks.d/ansible-pull owner=root group=root mode=0755

    #- name: Create logrotate entry for ansible-pull.log
    #  template: src=templates/etc_logrotate.d_ansible-pull.j2 dest=/etc/logrotate.d/ansible-pull owner=root group=root mode=0644

    - name: Reboot system
      raw: reboot