---

- hosts: koombook
  roles:
     # - firstStart
     # - nginx
     # - dnsmasq
     # - hostapd
     # - iptables
     # - wikipedia
     # #- kalite
     # - monitoring
     # - ideasbox
     # - gutemberg
     # - appinventor
     # - mook
     #- mongodb
     - role: kiwix
       kiwixProject: wikipedia
       portProject: 8001
       when: ansible_hostname == 'KoomBook483'