---
#It will always be localhost
- hosts: localhost
  roles:
      - firstStart
      - nginx
      - dnsmasq
      - hostapd
      - iptables
      - wikipedia
      #- kalite
      - monitoring
      - ideasbox
      - gutemberg
      - appinventor
      - mook
      - mongodb
    # Play a role for a specific device
    #- { role: mook, when: ansible_hostname == 'KoomBook918' }
    #- { role: mongodb, when: ansible_hostname == 'KoomBook918' }
