---
- hosts: localhost
  roles:
      - system
      - firstStart
      - nginx
      - dnsmasq
      - hostapd
      - iptables
      - kiwix
      #- kalite
      - monitoring
      - ideasbox
      - gutemberg
      - appinventor
      - bsfcampus
      - mongodb
    # Play a role for a specific device
    #- { role: bsfcampus, when: ansible_hostname == 'KoomBook918' }
    #- { role: mongodb, when: ansible_hostname == 'KoomBook918' }
