---

- stat: path=/etc/firstStart.csv
  register: st

- set_fact: kb_name="KoomBook{{ 1000 | random }}" UUID="{{ ansible_default_ipv4["macaddress"] | hash('md5') }}"
  when: st.stat.exists == False

- stat: path=/media/hdd/
  register: p

- set_fact: hdd_access="0"
  when: p.stat.isdir is not defined

- shell: echo "{{ kb_name }}","{{ UUID }}","{{hdd_access}}" >> /etc/firstStart.csv
  when: st.stat.exists == False
  
- shell: cat /etc/firstStart.csv | ssh {{ central_server }} "cat >> /home/jails/ansible/UUIDKoomBook/firstStart.csv"
  when: st.stat.exists == False

- template: src=interfaces.j2 dest=/etc/network/interfaces backup=no
  when: st.stat.exists == False

- command: /sbin/halt
  when: st.stat.exists == False