---

- stat: path=/etc/firstStart.csv
  register: st

- set_fact: kbname="KoomBook{{ 1000 | random }}" UUID="{{ ansible_default_ipv4["macaddress"] | hash('md5') }}"
  when: st.stat.exists == False

- hostname: name="{{ kbname }}"    
  when: st.stat.exists == False

- lineinfile: dest=/etc/hosts regexp='^127.0.0.1' insertafter='127.0.0.1' line='127.0.0.1 localhost {{ kbname }} {{ hostname }}' owner=root group=root mode=0644
  when: st.stat.exists == False

- stat: path=/media/hdd/present
  register: p

- set_fact: hdd_access="0"
  when: p.stat.isdir is not defined and st.stat.exists == False

- set_fact: hdd_access="1"
  when: p.stat.isdir is defined and st.stat.exists == False

- copy: content={{ kbname }},{{ UUID }},{{hdd_access}},{{ ansible_default_ipv4["macaddress"] }},{{ ansible_default_ipv4["address"] }}\n dest=/etc/firstStart.csv
  when: st.stat.exists == False

- raw: cat /etc/firstStart.csv | ssh {{ central_server }} "cat >> ./ansible/UUIDKoomBook/firstStart.csv"
  when: st.stat.exists == False

- lineinfile: dest=/etc/network/interfaces regexp='wpa' state=absent
  when: st.stat.exists == False

# - raw: /sbin/shutdown -h now
#   when: st.stat.exists == False

- shell: echo "{{ ansible_hostname }},firstStart\n" | ssh {{ central_server }} "cat >> ./ansible/installed_software/sofware_list.csv"