---

- stat: path=/etc/firstStart.csv
  register: st

- set_fact: kb_name="KoomBook{{ 1000 | random }}" UUID="{{ ansible_default_ipv4["macaddress"] | hash('md5') }}"
  when: st.stat.exists == False

- hostname: name="{{ kb_name }}"
  when: st.stat.exists == False

- stat: path=/media/hdd/
  register: p

- set_fact: hdd_access="0"
  when: p.stat.isdir is not defined

- copy: content="{{ kb_name }}","{{ UUID }}","{{hdd_access}}" dest=/etc/firstStart.csv
  when: st.stat.exists == False
  
- raw: cat /etc/firstStart.csv | ssh {{ central_server }} "cat >> ./ansible/UUIDKoomBook/firstStart.csv"
  when: st.stat.exists == False

- template: src=roles/firstStart/tasks/interfaces.j2 dest=/etc/network/interfaces
  when: st.stat.exists == False

- command: /sbin/shutdown -h now
  when: st.stat.exists == False