---
# For ARM
# - name: Check if package exist
#   stat: path=/tmp/ideasbox_{{ version }}_armhf.deb
#   register: st
#   when: ansible_architecture == 'armhf' or ansible_architecture == 'armv7l'

- name: Create storage dir for IdeasServer
  file: path=/media/hdd/ideasServer/storage state=directory mode=0755

- name: Copy IdeasServer package
  get_url: url={{filer_bsf}}/ideasbox_{{ version }}_armhf.deb dest=/tmp/ideasbox_{{ version }}_armhf.deb owner=root group=root mode=755
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"

- name: install IdeasServer package
  apt: deb=/tmp/ideasbox_{{ version }}_armhf.deb
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"

- name: Add IDEASBOX_ID
  lineinfile: dest=/etc/default/ideasbox
              regexp='^'
              line='IDEASBOX_ID={{ IdeasServer_id }}'
              state=present
  when: ansible_architecture == 'armhf' or ansible_architecture == 'armv7l'

# For AMD64
# - name: Check if package exist
#   stat: path=/tmp/ideasbox_{{ version }}_amd64.deb
#   register: st
#   when: ansible_architecture == 'x86_64'

- name: Copy IdeasServer package
  get_url: url={{filer_bsf}}/ideasbox_{{ version }}_amd64.deb dest=/tmp/ideasbox_{{ version }}_amd64.deb owner=root group=root mode=755
  when: ansible_architecture == 'x86_64'

- name: install IdeasServer package
  apt: deb=/tmp/ideasbox_{{ version }}_amd64.deb
  when: ansible_architecture == 'x86_64'

- tasks:
  include: ../../../post_tasks.yml task=IdeasServer version={{ version }}